project: 
  type: website

website: 
  title: "Sean Vieau Portfolio"
  navbar:
    background: primary
    left: 
      - href: index.qmd
        text: Home
      - text: Advanced Data Analyses (R/SAS)
        menu:
          - text: Regression (R)
            href: Project_1_Regression/Project_1_Regression_R/Project_1_Regression.qmd
          - text: Regression (SAS)
            href: Project_1_Regression/Project_1_Regression_SAS/Project_1_Regression_SAS.qmd
          - text: MLR With Confounding and Interaction (R)
            href: Project_2/Project_2_R/Code/Project2.qmd
          - text: Linear Mixed Model (R)
            href: Project_2/Project_2_R/Code/Project2LMM.qmd
          - text: Linear Mixed Model (SAS)
            href: Project_2/Project_2_SAS/Code/Linear_Mixed_Model_SAS.qmd
          - text: Predictive Modelling (R)
            href: Project_3_Predictive_Modelling/Project_3_R/Code/Project_3_Predictive_Modelling.qmd
          - text: Predictive Modelling (SAS)
            href: Project_3_Predictive_Modelling/Project_3_SAS/Code/Project_3_Predictive_Modelling_SAS.qmd
      - text: Data Wrangling (Python)
        href: Data_Wrangling/Treadmill_Data_Cleaning/Code/Automated_Treadmill_Data_Cleaning.qmd
      - text: Data Management (SAS)
        menu:
          - text: Project 1 - Importing
            href: Data_Management_(SAS)/Project_1/Project_1_Importing.qmd
          - text: Project 3 - Data Set Creation
            href: Data_Management_(SAS)/Project_3/Project3.qmd
          - text: Project 5 - Report and Analysis
            href: Data_Management_(SAS)/Project_5/Project_5_Report_and_Analysis.qmd
      - text: Statistical Consulting (R)
        menu:
          - text: Scope of Work and Negative Binomial Regression (R)
            href: Statistical_Consulting/Vieau_Project_01/Code/Megan_Watson_Project.qmd
      - text: Data Viz (R)
        menu:
          - text: Clinical Trials Visualization App
            href: https://6tendm-sean-vieau.shinyapps.io/Clinical_Trials_Visualization_App/
          - text: Animated Plots (R)
            href: Data_Visualization/Cancer_Animations/Gapminder_Cancer_Animations.qmd
          - text: Geospatial Analysis (R)
            href: Statistical_Consulting/Opioid_Epidemic/GeoSpatial_Opioid_Epidemic.qmd
      - text: Publications/Presentations
        href: Resume/Publications_and_Presentations.qmd
      
theme: minty

execute: 
  echo: true